# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: sample_app
  pool: 5
  timeout: 5000
  username: ruby
  password: RoRails

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: sample_app_test
  pool: 5
  timeout: 5000
  username: ruby
  password: RoRails

